Fix/bugs with starting jobs
equinor/dm-app-analysis-platform pull request #21
Opened 2023-03-01 13:23 UTC by KristianKjerstad

## What does this pull request change?

## Why is this pull request needed?

## Issues related to this change

2023-03-01 13:33 UTC, KristianKjerstad commented
must wait for https://github.com/equinor/dm-core-packages/pull/105 before this starts working

2023-03-01 13:59 UTC, soofstad requested changes

2023-03-01 13:59 UTC, soofstad commented on job_handlers/azure_container_instances/__init__.py
> +            self.azure_valid_container_name = "azure_container_job"
"name" does not seem to be specified in the blueprints for "AzureContainer".
So we should ether add it as a required attribute, or remove the need for it here completely.
I'd say add it.

2023-03-20 07:49 UTC, KristianKjerstad commented
@netr0m @soofstad @eoaksnes @ingeridhellen ready for review

2023-03-20 08:40 UTC, soofstad approved these changes

2023-03-20 09:19 UTC, merged